// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-mi8nwHZ_e3xmQClvoOQn0d17cGGbgU',
    appId: '1:480094027690:web:57107a6a2eef95a207b5d3',
    messagingSenderId: '480094027690',
    projectId: 'mobile2-7f054',
    authDomain: 'mobile2-7f054.firebaseapp.com',
    storageBucket: 'mobile2-7f054.firebasestorage.app',
    measurementId: 'G-NFWEENT7CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMQGL4O3aPZMuVU45XdfUuuYTAq41hFMQ',
    appId: '1:480094027690:android:b79d613de9f5068d07b5d3',
    messagingSenderId: '480094027690',
    projectId: 'mobile2-7f054',
    storageBucket: 'mobile2-7f054.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM-mi8nwHZ_e3xmQClvoOQn0d17cGGbgU',
    appId: '1:480094027690:web:ecb209b90d5f6aa107b5d3',
    messagingSenderId: '480094027690',
    projectId: 'mobile2-7f054',
    authDomain: 'mobile2-7f054.firebaseapp.com',
    storageBucket: 'mobile2-7f054.firebasestorage.app',
    measurementId: 'G-YQV7DTBDGM',
  );
}
